services:
  backend:
    container_name: hms-backend
    build:
      context: ./mroh-rfs-backend
      dockerfile: Dockerfile
      # args:
        # - DB_HOST=${DB_HOST}
        # - DB_NAME=${DB_NAME}
        # - DB_USERNAME=${DB_USERNAME}
        # - DB_PASSWORD=${DB_PASSWORD}
        # - TENANT_UUID=${TENANT_UUID}
        # - CLIENT_UUID=${CLIENT_UUID}
        # - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
    # env_file: ./mroh-rfs-backend/.env
    ports:
      - "8085:8085"
 
  frontend:
    container_name: hms-frontend
    build:
      context: ./mroh-rfs-frontend
      dockerfile: Dockerfile
      args:
        - MSAL_CLIENT_ID=${MSAL_CLIENT_ID}
        - MSAL_AUTHORITY_TENANT_ID=${MSAL_AUTHORITY_TENANT_ID}
        - MSAL_AUTHORITY_POLICY=${MSAL_AUTHORITY_POLICY}
        - PUBLIC_URL=${PUBLIC_URL}
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_API_VERSION=${REACT_APP_API_VERSION}
    env_file: ./mroh-rfs-frontend/.env
    ports:
      - '80:80'
    depends_on:
      - backend