services:
  backend:
    container_name: hms-backend
    build:
      context: ./mroh-rfs-backend
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    env_file: ./mroh-rfs-backend/.env
    ports:
      - "8085:8085"
 
  frontend:
    container_name: hms-frontend
    build:
      context: ./mroh-rfs-frontend
      dockerfile: Dockerfile
      args:
        - MSAL_CLIENT_ID=${MSAL_CLIENT_ID}
        - MSAL_AUTHORITY_TENANT_ID=${MSAL_AUTHORITY_TENANT_ID}
        - MSAL_AUTHORITY_POLICY=${MSAL_AUTHORITY_POLICY}
        - PUBLIC_URL=${PUBLIC_URL}
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_API_VERSION=${REACT_APP_API_VERSION}
    env_file: ./mroh-rfs-frontend/.env
    ports:
      - '80:80'
    depends_on:
      - backend